version: '3.3'
services:
  dev_db:
    image: mysql:8.0
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dev_db_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev_db

  test_db:
    image: mysql:8.0
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test_db_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
